name: Dart

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Install Java
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      # Install flutter
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.22.4'

      - name: Print Flutter/Dart version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      # Uncomment this step to verify the use of 'dart format' on each commit.
      # - name: Verify formatting
      #   run: dart format --output=none --set-exit-if-changed .

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source (type checking, etc)
        run: flutter analyze

      # Run flutter tests
      - name: Run tests
        run: flutter test
